const data = [
    {
        id: 1,
        company: 'Nintendo',
        category: 'Console',

        name: 'Nintendo Switch lite',
        Description: 'Nintendo Switch lite',
        price: 199,
        img: '/src/assets/lite.png',

    },
    {
        id: 2,
        company: 'Nintendo',
        category: 'Console',
        name: 'Nintendo Switch',
        Description: 'Nintendo Switch normal edition',
        price: 299,
        img: 'src/assets/switch.png',
    },
    {
        id: 3,
        company: 'Nintendo',
        category: 'Console',
        name: 'Nintendo Switch oled',
        Description: 'Nintendo Switch Oled, oled color',
        price: 349,
        img: 'src/assets/OLed.png',
    },
    {
        id: 4,
        company: 'Nintendo',
        category: 'Console',
        name: ' New Nintendo 3ds xl',
        Description: 'New Nintendo 3ds xl ',
        price: 150,
        img: 'src/assets/3ds.png',
    },
    {
        id: 5,
        company: 'Nintendo',
        category: 'Controll',
        name: 'Pro controller',
        Description: 'Nintendo switch pro controller ',
        price: 59,
        img: 'src/assets/procontrollerswitch.png',
    },
    {
        id: 6,
        company: 'Nintendo',
        category: 'controll',
        name: 'Nintendo switch joycons',
        Description: 'Nintendo Switch Joycons green and pink',
        price: 49,
        img: 'src/assets/joicons.png',

    },
    {
        id: 7,
        company: 'Nintendo',
        category: 'Console',
        name: 'Nintendo Switch Oled',
        Description: 'Nintendo Switch Oled edition special,Zelda ',
        price: 450,
        img: 'src/assets/editionpecial.png',
    },
    {
        id: 8,
        company: 'Nintendo',
        category: 'Console',
        name: 'Nintendo Switch Oled',
        Description: 'Nintendo Switch Oled edition special, Mario',
        price: 450,
        img: 'src/assets/ood.png',
    },
    {
        id: 9,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 4 old 500gb',
        Description: 'PS4 old version (2013) ',
        price: 199,
        img: 'src/assets/normalplay4.png',
    },
    {
        id: 10,
        company: 'Sony',
        category: 'Console',
        name: 'PLay Station 4 Pro',
        Description: 'PS4 PRO 1TB',
        price: 300,
        img: 'src/assets/play4pro.png',
    },
    {
        id: 11,
        company: 'Sony',
        category: 'Console',
        name: 'PLay Station 4 slim',
        Description: 'PS4 slim 800gb',
        price: 250,
        img: 'src/assets/play4.png',
    },
    {
        id: 12,
        company: 'Sony',
        category: 'Console',
        name: 'PS Vita',
        Description: 'PS Vita',
        price: 100,
        img: 'src/assets/psvita.png',
    },
    {
        id: 13,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 5 800gb ',
        Description: 'PLay Station 5 800gb without reader',
        price: 399,
        img: 'src/assets/plsy5.png',
    },
    {
        id: 14,
        company: 'Sony',
        category: 'Controll',
        name: 'PS4 Controller',
        Description: 'PS4 Controller',
        price: 49,
        img: 'src/assets/controllps4.png',
    },
    {
        id: 15,
        company: 'Sony',
        category: 'Controll',
        name: 'P54 Controller',
        Description: 'PS5 Controller',
        price: 79,
        img: 'src/assets/ps5controll.png',
    },
    {
        id: 16,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 5 1TB ',
        Description: 'PLay Station 5 800gb with reader',
        price: 499,
        img: 'src/assets/ps5reader.png',
    },
    {
        id: 17,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox Series X ',
        Description: 'Xbox Series X 1TB ',
        price: 499,
        img: 'src/assets/seriesx.png',
    },
    {
        id: 18,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox Series S ',
        Description: 'Xbox Series S 1TB Black ',
        price: 349,
        img: 'src/assets/xboxnegra.png',
    },
    {
        id: 19,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox Series S ',
        Description: 'Xbox Series S 1TB White ',
        price: 349,
        img: 'src/assets/xbox.png',
    },
    {
        id: 20,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox One X ',
        Description: 'Xbox One X 1TB Black ',
        price: 399,
        img: 'src/assets/onex.png',
    },
    {
        id: 21,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox One Old ',
        Description: 'Xbox One Old (2013) ',
        price: 149,
        img: 'src/assets/xboxone.png',
    },
    {
        id: 22,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox One S ',
        Description: 'Xbox One S  ',
        price: 250,
        img: 'src/assets/xboxones.png',
    },
    {
        id: 23,
        company: 'Xbox',
        category:'Controll',
        name: 'Xbox  Controller',
        Description: 'Xbox Controller',
        price: 59,
        img: 'src/assets/controlxbox.png',
    },
    {
        id: 24,
        company: 'Xbox',
        category:'Console',
        name: 'Xbox One S ',
        Description: 'Xbox One S GW edition',
        price: 300,
        img: 'src/assets/gears.png',
    },
    {
        id: 25,
        company: 'Nintendo',
        category:'Console',
        name: 'Wii U',
        Description: 'Nintendo Wii u',
        price: 150,
        img: 'src/assets/wiiu.png',
    },
    {
        id: 26,
        company: 'Nintendo',
        category:'Console',
        name: 'Wii ',
        Description: 'Nintendo Wii ',
        price: 100,
        img: 'src/assets/wii.png',
    },
    {
        id: 27,
        company: 'Nintendo',
        category:'Console',
        name: 'GameCub ',
        Description: 'Nintendo GameCub',
        price: 100,
        img: 'src/assets/gamecube.png',
    },
    {
        id: 28,
        company: 'Nintendo',
        category:'Console',
        name: 'Nintendo 64 ',
        Description: 'Nintendo 64',
        price: 59,
        img: 'src/assets/n64.png',
    },
    {
        id: 29,
        company: 'Nintendo',
        category:'Console',
        name: 'SNES ',
        Description: ' Super Nintendo Entertainment System',
        price: 59,
        img: 'src/assets/snes.png',
    },
    {
        id: 30,
        company: 'Nintendo',
        category:'Console',
        name: 'NES ',
        Description: '  Nintendo Entertainment System',
        price: 59,
        img: 'src/assets/nes.png',
    },
    {
        id: 31,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 3 ',
        Description: 'PLay 3 fat',
        price: 199,
        img: 'src/assets/ps3fat.png',
    },
    {
        id: 32,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 3 Slim ',
        Description: 'PLay 3 Slim',
        price: 210,
        img: 'src/assets/ps3.png',
    },
    {
        id: 33,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 2 ',
        Description: 'PLay Station 2 fat',
        price: 60,
        img: 'src/assets/play2fat.png',
    },
    {
        id: 34,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station 2 ',
        Description: 'PLay Station 2 Slim',
        price: 70,
        img: 'src/assets/ps2.png',
    },
    {
        id: 35,
        company: 'Sony',
        category: 'Console',
        name: ' PLay Station  ',
        Description: 'PLay Station',
        price: 30,
        img: 'src/assets/ps1.png',
    },
    {
        id: 36,
        company: 'Xbox',
        category:'Console',
        name: ' Xbox 360 ',
        Description: 'Microsoft Xbox 360',
        price: 99,
        img: 'src/assets/xbox360.png',
    },
    
   
]
export default data;